
sudo: required
services:
    - docker
before_install:
    - docker build -t jomonjames/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true jomonjames/react-test npm test
after_success:
    - docker build -t jomonjames/multi-client -f ./client/Dockerfile
    - docker build -t jomonjames/multi-nginx -f ./nginx/Dockerfile
    - docker build -t jomonjames/multi-server -f ./server/Dockerfile
    - docker build -t jomonjames/multi-worker -f ./worker/Dockerfile
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jomonjames/multi-client
    - docker push jomonjames/multi-nginx
    - docker push jomonjames/multi-server
    - docker push jomonjames/multi-worker
